# Schema for the configuration files of the candidat vote module.
candidat_vote.settings:
  type: config_object
  label: 'candidat vote settings'
  mapping:
    style_image:
      type: string
      label: 'Style image'
